// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.9.1,
// any modifications will be overwritten.
// ==============================================================

package com.maplecloudy.osrt.model.maven;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Information about one of the committers on this project.
 *
 * @version $Revision$ $Date$
 */
@SuppressWarnings("all")
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class Developer extends Contributor
    implements java.io.Serializable, Cloneable {

  //--------------------------/
  //- Class/Member Variables -/
  //--------------------------/

  /**
   * The unique ID of the developer in the SCM.
   */
  private String id;

  //-----------/
  //- Methods -/
  //-----------/

  /**
   * Method clone.
   *
   * @return Developer
   */
  public Developer clone() {
    try {
      Developer copy = (Developer) super.clone();

      return copy;
    } catch (Exception ex) {
      throw (RuntimeException) new UnsupportedOperationException(
          getClass().getName() + " does not support clone()").initCause(ex);
    }
  } //-- Developer clone()

  /**
   * Get the unique ID of the developer in the SCM.
   *
   * @return String
   */
  public String getId() {
    return this.id;
  } //-- String getId()

  /**
   * Set the unique ID of the developer in the SCM.
   *
   * @param id
   */
  public void setId(String id) {
    this.id = id;
  } //-- void setId( String )

}
